// CONSTANTS
export const INIT = 'INIT';
const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
export const MAP_CONFIG_INSTANCE = `${BACKEND_URL}/api/conf/instance`;
export const MAP_CONFIG_KEPLER = `${BACKEND_URL}/api/conf/kepler`;
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const FETCHING_CONFIG = 'FETCHING_CONFIG';
export const FETCHING_CONFIG_SUCCESS = 'FETCHING_CONFIG_SUCCESS';
export const FETCHING_DATA_ERROR = 'FETCHING_DATA_ERROR';

export const LOAD_REMOTE_RESOURCE_SUCCESS = 'LOAD_REMOTE_RESOURCE_SUCCESS';
export const LOAD_MAP_SAMPLE_FILE = 'LOAD_MAP_SAMPLE_FILE';
export const UPDATE_INSTANCE_CONFIGURATION = 'UPDATE_INSTANCE_CONFIGURATION';
